# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 5210
    connection-timeout: 5s
    servlet:
      context-path: /${spring.application.name}

spring:
    application: 
        name: attemper
    # 环境 dev|test|prod
    profiles:
        active: dev
    redis:
        open: true  # 是否开启redis缓存  true开启   false关闭
        database: 0
        host: localhost
        port: 6379
        password:       # 密码（默认为空）
        time: 6s  # 连接超时时长（毫秒）
        jedis:
            pool:
                max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
                max-wait: -1s      # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-idle: 10      # 连接池中的最大空闲连接
                min-idle: 5       # 连接池中的最小空闲连接
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        hikari:
            first:
                minimum-idle: 10
                maximum-pool-size: 100
                pool-name: first
                connection-timeout: 30000
                idle-timeout: 600000
                max-lifetime: 1800000
                connection-test-query: select 1
            second:
                minimum-idle: 10
                maximum-pool-size: 100
                pool-name: second
                connection-timeout: 30000
                idle-timeout: 600000
                max-lifetime: 1800000
                connection-test-query: select 1
    jpa: 
        hibernate: 
            ddl-auto: none
    jackson: 
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        defaultPropertyInclusion: non_null   #非空node才序列化
        deserialization: 
            FAIL_ON_UNKNOWN_PROPERTIES: false #未定义的key不序列化
      

# Mybatis配置
mybatis:
    mapperLocations: classpath*:mapper/*Mapper.xml
    configuration:
      map-underscore-to-camel-case: true
      variables:
        tablePrefix: attemper_
# eureka        
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application_instance_id:${random.value}}
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    region: default
    availabilityZones:
      default: defaultZone
    preferSameZone: false

superTenant:
  id: attemper