spring:
    datasource:
        hikari:
            first: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/attemper?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                username: root
                password: 123456
            second: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/log?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                username: root
                password: 123456

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  web:
    enable-scheduling: false
  scheduler:
    name: scheduler
    delayedInSecond: 5
    context-path: /
  executor:
    name: executor
    context-path: /
  snow-flake:
    data-center-id: 0
    machine-id: 1

org:
  quartz:
    jobStore:
      isClustered: true

logging:
  level:
    com.github.attemper: debug

camunda:
  bpm:
    history-level: full
