spring:
    datasource:
        hikari:
            first: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/attemper?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                username: root
                password: 123456
            second: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/log?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                username: root
                password: 123456

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  scheduler:
    name: scheduler
    context-path: ${app.scheduler.name}
    delayedInSecond: 5
  web:
    enable-scheduling: true
  snow-flake:
    data-center-id: 0
    machine-id: 1

logging:
  level:
    com.github.attemper.core.dao.mapper: debug

grpc:
    server:
      name: executor
      port: 5231

org:
  quartz:
    jobStore:
      isClustered: true
