spring:
    datasource:
        hikari:
            first: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/attemper?allowMultiQueries=true&characterEncoding=UTF-8
                username: root
                password: 123456
            second: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/log?characterEncoding=UTF-8
                username: root
                password: 123456
    mail:
        host: xxx
        username: xxx
        password: xxx
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  snow-flake:
    data-center-id: 0
    machine-id: 20

logging:
  level:
    com.github.attemper: debug