spring:
    datasource:
        hikari:
            first: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/attemper?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                username: root
                password: 123456
            second: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/log?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                username: root
                password: 123456
    jpa: 
        show-sql: true
        properties: 
            hibernate: 
                format-sql: true
                user_sql_comments: true

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

grpc:
    server:
      name: executor
      port: 5231

org:
  quartz:
    jobStore:
      isClustered: true

app:
  scheduler:
    delayedInSecond: 5