spring:
    datasource:
        hikari:
            first: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/attemper?allowMultiQueries=true&characterEncoding=UTF-8
                username: root
                password: 123456
            second: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/log?characterEncoding=UTF-8
                username: root
                password: 123456
    mail:
        host: xxx
        username: xxx
        password: xxx

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

app:
  web:
    enable-scheduling: true
  scheduler:
    delayedInSecond: 5
  executor:
    name: attemper-executor
    contextPath: /
  snow-flake:
    data-center-id: 0
    machine-id: 10

org:
  quartz:
    jobStore:
      isClustered: true
      misfireThreshold: 10000
      acquireTriggersWithinLock: true

logging:
  level:
    com.github.attemper: debug