server:
    port: 5211

spring:
    application: 
        name: attemper-scheduler
    profiles:
        active: dev
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        hikari:
            first:
                minimum-idle: 5
                maximum-pool-size: 100
                pool-name: first
                connection-timeout: 30000
                idle-timeout: 600000
                max-lifetime: 1800000
                connection-test-query: select 1
            second:
                minimum-idle: 5
                maximum-pool-size: 100
                pool-name: second
                connection-timeout: 30000
                idle-timeout: 600000
                max-lifetime: 1800000
                connection-test-query: select 1
    jackson: 
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        defaultPropertyInclusion: non_null   #非空node才序列化
        deserialization: 
            FAIL_ON_UNKNOWN_PROPERTIES: false #未定义的key不序列化
      

# Mybatis配置
mybatis:
    mapperLocations: classpath*:mapper/*Mapper.xml
    configuration:
        map-underscore-to-camel-case: true
        variables:
            tablePrefix: attemper_
            qrtzTablePrefix: ${org.quartz.jobStore.tablePrefix:QRTZ_}
# eureka
eureka:
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application_instance_id:${random.value}}
    preferIpAddress: true
  client:
    fetchRegistry: true
    region: default
    availabilityZones:
      default: defaultZone
    preferSameZone: false