spring:
    datasource:
        hikari:
            first: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/thor?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                username: root
                password: 123456
            second: 
                jdbc-url: jdbc:mysql://127.0.0.1:3306/log?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
                username: root
                password: 123456
    jpa: 
        show-sql: true
        properties: 
            hibernate: 
                format-sql: true
                user_sql_comments: true

eureka:
  client:
    enabled: false
    serviceUrl:
      devZone: http://${EUREKA_IP:localhost}:${EUREKA_PORT:8761}/${REGISTRY_NAME:eureka}/


logging:
  level:
    com.thor.core.dao.mapper: debug

stark:
  eurekaZone: ${eureka.client.serviceUrl.devZone}
  serviceUrls: http://localhost:5200/
  serviceName: stark
  tenantId: stark
  sign: 2fbb71b04b02738300427866d6e3181a
